version: "3.1"
services:
  localstack:
    image: localstack/localstack
    container_name: "sms-localstack"
    environment:
      - SERVICES=sqs, cloudformation, s3, lambda, sts, apigateway, iam, route53
      - EDGE_PORT=4566
      - AWS_DEFAULT_REGION=us-east-1
      - DEFAULT_REGION=us-east-1
      - LAMBDA_REMOTE_DOCKER=false
      - LAMBDA_EXECUTOR=docker
      - DEBUG=1
    ports:
      - "4566-4597:4566-4597"
    volumes:
      - "${TEMPDIR:-/tmp/localstack}:/temp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
