version: "3.1"
services:
  localstack:
    image: localstack/localstack
    environment:
      - EDGE_PORT=4566
      - SERVICES=lambda,s3,cloudformation,sts,apigateway,iam,route53,secretsmanager
      - LAMBDA_REMOTE_DOCKER=false
      - DEBUG=1
    ports:
      - "4566-4597:4566-4597"
    volumes:
      - "${TEMPDIR:-/tmp/localstack}:/temp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
