service: ses2slack
frameworkVersion: "2"
plugins:
  - serverless-localstack

custom:
  defaultStage: local
  localstack:
    debug: true
    autostart: true
    lambda:
      mountCode: true
    docker:
      sudo: false
    stages:
      - local
      - dev
    endpointFile: localstack_endpoints.json
  profiles:
    local: sls-us-east-1-local
    dev: sls-us-east-1-dev
    st: sls-us-east-1-st
    prod: sls-us-east-1-prod

provider:
  name: aws
  runtime: nodejs12.x
  region: ${env:AWS_REGION}
  stage: ${opt:stage, self:custom.defaultStage} # 引数のstageを優先、なければデフォルト
  profile: ${self:custom.profiles.${self:provider.stage}} # stageに応じたprofile名をcustomで指定
  lambdaHashingVersion: "20201221"
  apiGateway:
    shouldStartNameWithService: true
  environment:
    SLACK_WEB_HOOK_URL: ${env:SLACK_WEB_HOOK_URL}
    S3_MAIL_BUCKET_NAME: ses2slack-mail-${self:provider.stage}

functions:
  execute:
    handler: handler.mailToSlack

resources:
  Resources:
    Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:provider.environment.S3_MAIL_BUCKET_NAME}
