service: ses2slack
frameworkVersion: "2"
plugins:
  - serverless-localstack

custom:
  defaultStage: local
  awsAccountId: ${env:AWS_ACCOUNT_ID}
  localstack:
    debug: true
    autostart: true
    lambda:
      mountCode: true
    docker:
      sudo: false
    stages:
      - local
      - dev
    endpointFile: localstack_endpoints.json
  profile: slsfw-${self:provider.stage} # stageに応じたprofile名を指定
  environment:
    SLACK_WEB_HOOK_SECRET: ses2slack-hook-${self:provider.stage}
    S3_MAIL_BUCKET_NAME: ses2slack-mail-${self:provider.stage}
    AWS_REGION_NAME: ${env:AWS_REGION}

provider:
  name: aws
  runtime: nodejs12.x
  region: ${env:AWS_REGION}
  stage: ${opt:stage, self:custom.defaultStage} # 引数のstageを優先、なければデフォルト
  profile: ${self:custom.profile}
  lambdaHashingVersion: "20201221"
  apiGateway:
    shouldStartNameWithService: true
  environment: ${self:custom.environment}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:Get*
            - s3:List*
            - secretsmanager:Get*
          Resource: "*"

functions:
  execute:
    handler: handler.mailToSlack

resources:
  Resources:
    MailObjectBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ses2slack-mail-${self:provider.stage}
    MailObjectBucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: !Ref MailObjectBucket
        PolicyDocument:
          Statement:
            - Action:
                - s3:PutObject
              Effect: "Allow"
              Principal:
                Service: "ses.amazonaws.com"
              Resource: !Join
                - ""
                - - "arn:aws:s3:::"
                  - !Ref MailObjectBucket
                  - /*
              Condition:
                StringEquals:
                  "aws:Referer": ${opt:awsAccountId, self:custom.awsAccountId} # 引数のawsAccountIdを優先、なければenvから設定
