service: ses2slack
frameworkVersion: "2"
plugins:
  - serverless-localstack

custom:
  localstack:
    debug: true
    autostart: true
    lambda:
      mountCode: true
    docker:
      sudo: false
    stages:
      - local
      - dev
    endpointFile: localstack_endpoints.json

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: "20201221"
  apiGateway:
    shouldStartNameWithService: true

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get
